#!/usr/bin/env sh

sudo dnf install -y lxappearance arc-theme

# moka theme for icons
sudo dnf install -y numix-icon-theme

# notification daemon
sudo dnf install -y dunst
mkdir -p $HOME/.config/dunst
ln -s $BASEPATH/dunstrc-config $HOME/.config/dunst/dunstrc

# gtk theme config
mkdir -p $HOME/.config/gtk-3.0
ln -sf $BASEPATH/gtk-3.0-settings-config.ini $HOME/.config/gtk-3.0/settings.ini
ln -sf $BASEPATH/gtkrc-2.0-config $HOME/.gtkrc-2.0

ln -sf $BASEPATH/Xresources $HOME/.Xresources
