#!/usr/bin/env sh

# updates
sudo dnf update -y

sudo dnf update -y kernel*
sudo dnf install -y gcc kernel-devel kernel-headers dkms make bzip2 perl libxcrypt-compat
sudo dnf install -y python2-devel python3-devel


# vim
sudo dnf install -y vim

# base themes
source $BASEPATH/base_themes

# terminal and fonts
source $BASEPATH/terminal_and_fonts

# powerline
source $BASEPATH/powerline

# zsh
sudo dnf install -y zsh

# filemanagers
sudo dnf install -y thunar nemo pcmanfm

# rbenv and ruby
# source $BASEPATH/ruby_and_rbenv

# visual studio code
# source $BASEPATH/visual_studio_code



