#!/usr/bin/env sh

# updates
sudo dnf upgrade -y

sudo dnf upgrade -y kernel*
sudo dnf install -y gcc kernel-devel kernel-headers dkms make bzip2 perl libxcrypt-compat openssl-devel libyaml-devel libffi-devel readline-devel zlib-devel gdbm-devel ncurses-devel
sudo dnf install -y python2-devel python3-devel
sudo dnf install arandr

# chrome
sudo dnf install -y fedora-workstation-repositories
sudo dnf config-manager --set-enabled google-chrome
sudo dnf install -y google-chrome-stable

# networkmanager network ui
sudo dnf install -y NetworkManager-tui

# vim
sudo dnf install -y vim

# base themes
source $BASEPATH/base_themes_setup

# terminal and fonts
source $BASEPATH/terminal_and_fonts_setup

# powerline
source $BASEPATH/powerline_setup

# zsh
sudo dnf install -y zsh

# filemanagers
sudo dnf install -y thunar nemo pcmanfm

# rbenv and ruby
source $BASEPATH/rbenv_setup

# visual studio code
source $BASEPATH/visual_studio_code_setup



