#!/usr/bin/env sh

pip3 install pip
pip3 install setuptools
pip3 install psutil --user
pip3 install powerline-status --user

sudo dnf install -y powerline
sudo dnf install -y vim-powerline

mkdir -p $HOME/.config/powerline
ln -sf $BASEPATH/powerline-config.json $HOME/.config/powerline/config.json
