#!/usr/bin/env sh

# terminals
sudo dnf install terminator
sudo dnf install st
sudo dnf install xterm

# MidnightCommander
sudo dnf install mc

# set profile
ln -sf $BASEPATH/profile $HOME/.profile
ln -sf $BASEPATH/profile $HOME/.zprofile

# Fonts config
mkdir -p $HOME/.config/fontconfig
ln -sf $BASEPATH/fonts-fontconfig.conf $HOME/.config/fontconfig/fonts.conf

# fonts
LOCAL_FONTS_PATH=~/.local/share/fonts
mkdir -p $LOCAL_FONTS_PATH

sudo dnf install powerline-fonts

# Patched Fonts for VSCode integrated terminal in particular
cd $LOCAL_FONTS_PATH && curl -fLo "Inconsolata for Powerline Nerd Font Complete.otf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Inconsolata/complete/Inconsolata%20Nerd%20Font%20Complete.otf
cd $LOCAL_FONTS_PATH && curl -fLo "Inconsolata for Powerline Nerd Font Complete Mono.otf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Inconsolata/complete/Inconsolata%20Nerd%20Font%20Complete%20Mono.otf

# San Francisco OSx like fonts
cd $LOCAL_FONTS_PATH && curl -fLo "System San Francisco Display Bold.ttf" https://github.com/supermarin/YosemiteSanFranciscoFont/raw/master/System%20San%20Francisco%20Display%20Bold.ttf
cd $LOCAL_FONTS_PATH && curl -fLo "System San Francisco Display Regular.ttf" https://github.com/supermarin/YosemiteSanFranciscoFont/raw/master/System%20San%20Francisco%20Display%20Regular.ttf
cd $LOCAL_FONTS_PATH && curl -fLo "System San Francisco Display Thin.ttf" https://github.com/supermarin/YosemiteSanFranciscoFont/raw/master/System%20San%20Francisco%20Display%20Thin.ttf
cd $LOCAL_FONTS_PATH && curl -fLo "System San Francisco Display Ultralight.ttf" https://github.com/supermarin/YosemiteSanFranciscoFont/raw/master/System%20San%20Francisco%20Display%20Ultralight.ttf

# terminator configuration
mkdir -p $HOME/.config/terminator
ln -sf $BASEPATH/terminator-config $HOME/.config/terminator/config
