#!/usr/bin/env sh

set -e

# terminals
sudo dnf install terminator
sudo dnf install st
sudo dnf install xterm

# MidnightCommander
sudo dnf install mc

# fonts
LOCAL_FONTS_PATH=~/.local/share/fonts
mkdir -p $LOCAL_FONTS_PATH

sudo dnf install powerline-fonts
cd $LOCAL_FONTS_PATH && curl -fLo "Inconsolata for Powerline Nerd Font Complete.otf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Inconsolata/complete/Inconsolata%20Nerd%20Font%20Complete.otf
cd $LOCAL_FONTS_PATH && curl -fLo "Inconsolata for Powerline Nerd Font Complete Mono.otf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Inconsolata/complete/Inconsolata%20Nerd%20Font%20Complete%20Mono.otf

