#!/usr/bin/env sh

sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepo/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

sudo dnf install -y code

/usr/bin/code --install-extension vscodevim.vim
/usr/bin/code --install-extension vscodeintellicode
/usr/bin/code --install-extension material-icon-theme
/usr/bin/code --install-extension gitlens
/usr/bin/code --install-extension code-settings-sync
/usr/bin/code --install-extension beautify

mkdir -p $HOME/.config/Code/User
cp $BASEPATH/settings-config-Code-User.json $HOME/.config/Code/User/settings.json
